export enum NoteNames {
  CFlat = 'CFlat',
  C = 'C',
  CSharp = 'CSharp',
  DFlat = 'DFlat',
  D = 'D',
  DSharp = 'DSharp',
  EFlat = 'EFlat',
  E = 'E',
  F = 'F',
  FSharp = 'FSharp',
  GFlat = 'GFlat',
  G = 'G',
  GSharp = 'GSharp',
  AFlat = 'AFlat',
  A = 'A',
  ASharp = 'ASharp',
  BFlat = 'BFlat',
  B = 'B',
}
